### ISSUE TITLE
Date Format Error

### ISSUE THREAD

**Issue by cwbullet** [dsifford/academic-bloggers-toolkit#411]
**ABT Version:** 4.13.0

**PHP Version:** 5.6

**Theme:**  

**Plugin List:**
- Disabled all and still ge the error.  

  Safari 11.02

**Browser:** Google Chrome (Version: xxx)

**Expected behavior:**  
Adding a source manually or adding a webpage.  I would expect it to add the page and date accessed automatically.  I can edit them, but it will nto allow you to add the source.  It hangs and will not submit because it says the date is not int he correct format.  

**Actual behavior:**
It will not add the source because of a date format issue.  

**Console messages:**
```js
// Paste messages here

```

**Comment by dsifford** [comment]
Fixed in `v4.13.0`.

**Comment by cwbullet** [comment]
It is not fixed.  I get the same error.  
![screen shot](https://user-images.githubusercontent.com/22658819/34922318-ee34c324-f953-11e7-8187-b9350b862d72.png)

I will not allow you to submit.

**Comment by cwbullet** [comment]
I hit add reference and it does nothing.

**Comment by dsifford** [comment]
@cwbullet what browser are you using? Did you try clearing both your browser _and_ server cache?

**Comment by cwbullet** [comment]
I have used Chrome, Firefox, Safari.  I have cleared both the server and my browser cache.  I have deleted all plugins and I will can not add a website as a source.  It says the date format is incorrect.

**Comment by HoussenMoshine** [comment]
I can confirm, the bug is still here.

**Comment by dsifford** [comment]
Yikes! That's a nasty bug. Good catch. 

Working on getting this fixed now.

**Comment by cwbullet** [comment]
Yes.  The error is still in the lastest update.  Also, should there be more than one citation style to choose from?  

The last two - three updates have really caused form problems.

**Comment by dsifford** [comment]
Triple check that your cache had been fully cleared out. 

Re: only one style --- you should be able to query all 8500 as you begin typing.

**Comment by cwbullet** [comment]
Nope.  I tried with Google Chrome with a different computer that has never been to the site.  I turn off the cache.  I turn off all plugins and it still won't work.  I get the same date format error and it only shows "American Medical Association (sorted alphabetically)" format in the list.

**Comment by cwbullet** [comment]
Ok.  I see.  The citation style works.  I still get the date format error.

**Comment by dsifford** [comment]
Can you explain again exactly the error you're getting and what steps you take to trigger it?

**Comment by cwbullet** [comment]
Ok.  
1.  I click on the plus button to add a source.  
2.  I click "add manually".
3.  I type a link in autocite box.
4.  It loads the page information with the date.  
5.  I click "add reference" and it says there is a date format error even if it is correct.

**Comment by dsifford** [comment]
Aha.. So it's a date added by the autocite that triggers the error. Haven't investigated that. I'll look into it as soon as I can. (opening a new issue for that).
