### ISSUE TITLE
Cannot import references from .bib or .ris exported from Endnote

### ISSUE THREAD

**Issue by LindaEve** [dsifford/academic-bloggers-toolkit#428]
**ABT Version:**  4.13.3

**PHP Version:**  5.6.32 

**Theme:**  250 (Rutgers University custom theme)

**Plugin List:**
- Academic Blogger's Toolkit
- Broken Link Checker
- Contact Form 7
- Content Views
- Custom Meta Widget
- Flexy Breadcrumb
- ImpactPubs
- InfiniteWP - Client
- MetaSlider
- Shortcodes Ultimate
- TinyMCE Advanced
- Wordfence Security
- wpDirAuth

**Browser:** Firefox 57.0.4

**Expected behavior:** Expected to be able to import a reference list from a RIS or BIB file

**Actual behavior:** Tried to select file and got a message "Error The selected file could not be processed"

**Console messages:**
```js
// Paste messages here

```

**Comment by dsifford** [comment]
Thanks for the report.

Can you share one or both of the files you're trying to import so I can try and see what's causing the issue? 

Thanks

**Comment by LindaEve** [comment]
Sure, thank you. Both files are attached here.


Linda

________________________________

**Comment by dsifford** [comment]
Thanks @LindaEve 

If not too much trouble, would you mind dragging and dropping the file into this issue thread on GitHub when you get a chance? Reason being: There are sometimes hidden characters in the file that cause the issue. Just want to be certain the file I'm trying is identical to the one that triggered your issue. 

Thanks

**Comment by LindaEve** [comment]
Hi Derek
I had to rename them as .txt files to get them to upload here, but anyway, here they are.
[FlowCyt.bib.txt](https://github.com/dsifford/academic-bloggers-toolkit/files/1687879/FlowCyt.bib.txt)
[FlowCyt.ris.txt](https://github.com/dsifford/academic-bloggers-toolkit/files/1687880/FlowCyt.ris.txt)

Thanks so much!
Linda

**Comment by glorious1** [comment]
@LindaEve, Your files have Windows line endings (CR LF).  Unless something has changed, you need to change them to Unix (LF) and they will hopefully work.

**Comment by dsifford** [comment]
@glorious1 Windows line endings should work now to my knowledge. I explicitly went in and fixed that. Let me know if that is not the case.

**Comment by LindaEve** [comment]
@dsifford It still does not work. 
@glorious1 I appreciate your input but I have no idea how to change the line endings and I'm not sure it's really worth it.

**Comment by glorious1** [comment]
Another issue I noticed with importing files is fields that have multiple lines with line endings within them. I'm not sure it still does, but in my early testing that prevented import.  Try editing your RIS file so it has just a couple of references, and get rid of multiple lines in fields.  In your file I see it in the  N1 and KW fields.  You could just delete those fields.
If you have the option to select fields to be exported from EndNote into the RIS or BIB file, I would restrict it to just the fields you need to build the reference - it might help avoid problems like this.

**Comment by LindaEve** [comment]
@glorious1 I tried getting rid of any field with line breaks and that more or less worked. Sadly I am still not finding the plugin really works for me. What I really need is the ability to import a publication list based on a PubMed search (like an author or a serious of PMIDs or a grant number... that sort of thing). And I need just a nice list of publications that is not dependent on in-text citations.

**Comment by dsifford** [comment]
@glorious1 bibtex import is available. Also, "list-type" fields where there are the same field on mulitple lines (eg, `KW` are also supported). If these things are not working, open an issue and provide an example of that here: https://github.com/dsifford/astrocite

@LindaEve What you are describing is also supported. Check out the wiki page for "static publication list"

https://github.com/dsifford/academic-bloggers-toolkit/wiki

**Comment by glorious1** [comment]
There is a way to enter a list of pmid’s, from the plus sign. Also you can generate a static reference list (no citations) through the second row of icons.

**Comment by dsifford** [comment]
Closing this thread since (I think) this has already been fixed? Reopen if not...
